const initialData = {
  movies: [
    {
      'title': 'Film 1',
      'id': 'film1',
      'genre': 'documentary',
      'posterPath': '',
      'alt': 'Cool poster',
      'release_date': '2016-12-29',
      'runtime': '220',
      'overview': 'Lorem ipsum',
      'vote_average': '4.3',
      'genres': ['comedy', 'horror', 'documentary'],
    },
    {
      'title': 'Film 2',
      'id': 'film2',
      'genre': 'horror',
      'posterPath': '',
      'alt': 'Cool poster',
      'release_date': '2005-12-29',
      'runtime': '120',
      'overview': 'Lorem ipsum',
      'vote_average': '4.3',
      'genres': ['comedy', 'horror', 'documentary'],
    },
    {
      'title': 'Film 3',
      'id': 'film3',
      'genre': 'comedy',
      'posterPath': '',
      'alt': 'Cool poster',
      'release_date': '2019-12-29',
      'runtime': '160',
      'overview': 'Lorem ipsum',
      'vote_average': '4.3',
      'genres': ['comedy', 'horror', 'documentary'],
    },
    {
      'title': 'Film 4',
      'id': 'film4',
      'genre': 'crime',
      'posterPath': '',
      'alt': 'Cool poster',
      'release_date': '2000-12-29',
      'runtime': '110',
      'overview': 'Lorem ipsum',
      'vote_average': '4.3',
      'genres': ['comedy', 'horror', 'documentary'],
    },
    {
      'title': 'Film 5',
      'id': 'film5',
      'genre': 'documentary',
      'posterPath': '',
      'alt': 'Cool poster',
      'release_date': '1980-12-29',
      'runtime': '130',
      'overview': 'Lorem ipsum',
      'vote_average': '4.3',
      'genres': ['comedy', 'horror', 'documentary'],
    },
    {
      'title': 'Film 6',
      'id': 'film6',
      'genre': 'crime',
      'posterPath': '',
      'alt': 'Cool poster',
      'release_date': '1936-12-29',
      'runtime': '140',
      'overview': 'Lorem ipsum',
      'vote_average': '4.3',
      'genres': ['comedy', 'horror', 'documentary'],
    }
  ]
};

export default initialData;
