const data = {
  movies: [
    {
      'title': 'Film 1',
      'id': 'film1',
      'genre': 'documentary',
      'posterPath': '',
      'alt': 'Cool poster',
      'releaseDate': '1992',
      'duration': '220',
      'description': 'Lorem ipsum',
      'rating': '4.3',
    },
    {
      'title': 'Film 2',
      'id': 'film2',
      'genre': 'horror',
      'posterPath': '',
      'alt': 'Cool poster',
      'releaseDate': '2005',
      'duration': '120',
      'description': 'Lorem ipsum',
      'rating': '4.3',
    },
    {
      'title': 'Film 3',
      'id': 'film3',
      'genre': 'comedy',
      'posterPath': '',
      'alt': 'Cool poster',
      'releaseDate': '2019',
      'duration': '160',
      'description': 'Lorem ipsum',
      'rating': '4.3',
    },
    {
      'title': 'Film 4',
      'id': 'film4',
      'genre': 'crime',
      'posterPath': '',
      'alt': 'Cool poster',
      'releaseDate': '2000',
      'duration': '110',
      'description': 'Lorem ipsum',
      'rating': '4.3',
    },
    {
      'title': 'Film 5',
      'id': 'film5',
      'genre': 'documentary',
      'posterPath': '',
      'alt': 'Cool poster',
      'releaseDate': '1980',
      'duration': '130',
      'description': 'Lorem ipsum',
      'rating': '4.3',
    },
    {
      'title': 'Film 6',
      'id': 'film6',
      'genre': 'crime',
      'posterPath': '',
      'alt': 'Cool poster',
      'releaseDate': '1936',
      'duration': '140',
      'description': 'Lorem ipsum',
      'rating': '4.3',
    }
  ]
};

export default data;
